### ISSUE TITLE
Translation-sync push failed

### ISSUE THREAD

**Issue by phil-davis** [owncloud/twofactor_backup_codes#50]
https://drone.owncloud.com/owncloud/translation-sync/3059/32/12

```
+ git push origin master:master
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Changes must be made through a pull request. Required status check "continuous-integration/drone/pr" is expected.        
To github.com:owncloud/twofactor_backup_codes.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:owncloud/twofactor_backup_codes.git'
exit status 1
```

We did something in oC10 app repos a few months ago when the drone secrets changed, so that translation-sync would work. I forget what it is.

**Comment by phil-davis** [comment]
Settings have been adjusted by @xoxys - the next attempt tonight should work.

**Comment by xoxys** [comment]
Restarted the cron run manually already.

**Comment by phil-davis** [comment]
The commit has happened: https://github.com/owncloud/twofactor_backup_codes/commit/04a7d888ac4d19ddd36113201a198e1f148d3099
